name: Test
on:
  push:
    branches:
    - "*"
  pull_request: {}
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
    timeout-minutes: 5
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.x
    - name: Checkout
      uses: actions/checkout@v4
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --verbose
    - name: Test
      run: go test -v ./...
